sudo: false

language: go
go:
  - '1.10.3'

git:
  depth: 1

install:
  - go get -u github.com/golang/dep/cmd/dep
  - dep ensure
  - dep status

script:
  - go build -v -ldflags "-X main.version=${TRAVIS_TAG}" -a -o ./drone-passwordstate

after_success:
  - test $TRAVIS_TAG
  - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
  - export REPO=$DOCKER_REPO
  - docker build -f Dockerfile -t $REPO:$TRAVIS_TAG -t $REPO:latest .
  - docker push $REPO
